import type { Track, Stem } from "./types"

export const mockTracks: Track[] = [
  // Beats
  {
    id: "1",
    title: "Midnight Dreams",
    artist: "AudioLab",
    genre: "Hip Hop",
    category: "beat",
    bpm: 140,
    key: "C Minor",
    price: 29.99,
    description: "Dark atmospheric hip hop beat with heavy 808s and melodic piano",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    cover_image_url: "/dark-hip-hop-beat-cover.jpg",
    duration: 180,
    tags: ["dark", "atmospheric", "piano", "808"],
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Summer Vibes",
    artist: "AudioLab",
    genre: "Pop",
    category: "beat",
    bpm: 120,
    key: "G Major",
    price: 24.99,
    description: "Uplifting pop instrumental with catchy melodies and bright synths",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    cover_image_url: "/summer-pop-music-cover.jpg",
    duration: 200,
    tags: ["uplifting", "bright", "catchy", "synth"],
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Trap Energy",
    artist: "AudioLab",
    genre: "Trap",
    category: "beat",
    bpm: 150,
    key: "D Minor",
    price: 34.99,
    description: "High energy trap beat with hard hitting drums and aggressive synths",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    cover_image_url: "/trap-music-energy-cover.jpg",
    duration: 165,
    tags: ["energetic", "hard", "aggressive", "drums"],
    is_featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Lo-Fi Study",
    artist: "AudioLab",
    genre: "Lo-Fi",
    category: "beat",
    bpm: 85,
    key: "A Minor",
    price: 19.99,
    description: "Chill lo-fi beat perfect for studying or relaxing",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    cover_image_url: "/lofi-study-music-cover.jpg",
    duration: 220,
    tags: ["chill", "relaxing", "study", "ambient"],
    is_featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Samples
  {
    id: "7",
    title: "Vocal Chops Pack",
    artist: "AudioLab",
    genre: "Vocal",
    category: "sample",
    bpm: 0,
    key: "Various",
    price: 14.99,
    description: "50 high-quality vocal chops and phrases ready to use in your productions",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    cover_image_url: "/vocal-chops-sample-pack.jpg",
    duration: 0,
    tags: ["vocal", "chops", "phrases", "pack"],
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "8",
    title: "808 Bass Collection",
    artist: "AudioLab",
    genre: "Bass",
    category: "sample",
    bpm: 0,
    key: "Various",
    price: 19.99,
    description: "100 punchy 808 bass samples perfect for trap and hip hop",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    cover_image_url: "/808-bass-samples.jpg",
    duration: 0,
    tags: ["808", "bass", "trap", "hip hop"],
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "9",
    title: "Drum Loops Vol. 1",
    artist: "AudioLab",
    genre: "Drums",
    category: "sample",
    bpm: 0,
    key: "Various",
    price: 24.99,
    description: "75 professional drum loops in various genres and tempos",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    cover_image_url: "/drum-loops-pack.jpg",
    duration: 0,
    tags: ["drums", "loops", "percussion", "rhythms"],
    is_featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "10",
    title: "Synth Textures",
    artist: "AudioLab",
    genre: "Synth",
    category: "sample",
    bpm: 0,
    key: "Various",
    price: 17.99,
    description: "Atmospheric synth textures and pads for ambient productions",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    cover_image_url: "/synth-textures-ambient.jpg",
    duration: 0,
    tags: ["synth", "textures", "pads", "ambient"],
    is_featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // MIDI
  {
    id: "11",
    title: "Trap Melody MIDI",
    artist: "AudioLab",
    genre: "Trap",
    category: "midi",
    bpm: 140,
    key: "D Minor",
    price: 9.99,
    description: "Dark trap melody MIDI file with multiple variations",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    cover_image_url: "/trap-melody-midi.jpg",
    duration: 0,
    tags: ["trap", "melody", "dark", "midi"],
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "12",
    title: "Piano Chord Progressions",
    artist: "AudioLab",
    genre: "Piano",
    category: "midi",
    bpm: 0,
    key: "Various",
    price: 12.99,
    description: "20 beautiful piano chord progressions in MIDI format",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    cover_image_url: "/piano-chords-midi.jpg",
    duration: 0,
    tags: ["piano", "chords", "progressions", "midi"],
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "13",
    title: "Guitar Riffs MIDI Pack",
    artist: "AudioLab",
    genre: "Guitar",
    category: "midi",
    bpm: 0,
    key: "Various",
    price: 14.99,
    description: "15 guitar riff MIDI files for rock and pop productions",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
    cover_image_url: "/guitar-riffs-midi.jpg",
    duration: 0,
    tags: ["guitar", "riffs", "rock", "pop"],
    is_featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "14",
    title: "Bass Lines Collection",
    artist: "AudioLab",
    genre: "Bass",
    category: "midi",
    bpm: 0,
    key: "Various",
    price: 11.99,
    description: "Groovy bass line MIDI files for various genres",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
    cover_image_url: "/bass-lines-midi.jpg",
    duration: 0,
    tags: ["bass", "groovy", "funk", "midi"],
    is_featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    title: "Electronic Dreams",
    artist: "AudioLab",
    genre: "Electronic",
    category: "beat",
    bpm: 128,
    key: "E Minor",
    price: 27.99,
    description: "Futuristic electronic track with pulsing synths and driving bassline",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    cover_image_url: "/electronic-futuristic-music-cover.jpg",
    duration: 195,
    tags: ["futuristic", "synth", "bass", "electronic"],
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    title: "R&B Smooth",
    artist: "AudioLab",
    genre: "R&B",
    category: "beat",
    bpm: 95,
    key: "F Major",
    price: 29.99,
    description: "Smooth R&B instrumental with soulful keys and groovy bass",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    cover_image_url: "/rnb-smooth-soul-music-cover.jpg",
    duration: 210,
    tags: ["smooth", "soulful", "groovy", "keys"],
    is_featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockStems: Stem[] = [
  {
    id: "stem-1",
    track_id: "1",
    original_filename: "midnight-dreams.mp3",
    vocals_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    drums_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    bass_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    other_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    status: "completed",
    error_message: null,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "stem-2",
    track_id: "2",
    original_filename: "summer-vibes.wav",
    vocals_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    drums_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    bass_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    other_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    status: "completed",
    error_message: null,
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: new Date(Date.now() - 172800000).toISOString(),
  },
]
